config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :home
  resource :time_travel, only: [:create] if Rails.env.development? || Rails.env.staging?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/time_travels_controller.rb
class TimeTravelsController < ApplicationController

  def create
    tc_action = params[:tc_action]
    setting_time = Time.zone.parse(params[:tc_date]) if params[:tc_date].present?
    operation_name = ""
    result = case tc_action
             when "freeze"
               operation_name = "固定"
               Timecop.freeze(setting_time)
             when "travel"
               operation_name = "移動"
               Timecop.travel(setting_time)
             end
    if result
      flash[:notice] = "時刻を#{result}に#{operation_name}しました"
    else
      Timecop.return
      flash[:notice] = "時間を元に戻しました"
    end
    redirect_back(fallback_location: root_path)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/time_travels_helper.rb
module TimeTravelsHelper
end

app/views/home/index.slim
h1
  |現在時刻は#{Time.zone.now.strftime("%Y年%m月%d日 %H時%M分%S秒")}です

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTimetravelerSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <%= render "shared/time_traveler" %>
    <p>
      <%= flash[:notice] %>
    </p>
  </body>
</html>

app/views/shared/_time_traveler.slim
.gl-anchor style="right: 100px; bottom: 50px; position: fixed; z-index: 10000;"
  = form_tag(time_travel_path) do
    = text_field_tag :tc_date, Time.zone.now.strftime("%Y/%m/%d %H:%M:%S"), style: "width: 190px"
    = select_tag :tc_action, options_for_select({"移動": "travel", "固定": "freeze", "解除": "reset"})
    = submit_tag "時間を操作する"